In [3]:
import sys
sys.path.insert(0, './Fundamental/')
sys.path.insert(0, './TechIndicators/')
sys.path.insert(0, './Broker/')
from fundamental import fundamental
from account import *
from CPR import CPR, ABC
from testing import *
import backtrader as bt

# connect IB ac & get ac info
# account_values, bp, ib, df = account()
# df.to_csv(f"./HisData/DataStorage/StockData/testing.csv")
tarCsv = "./HisData/DataStorage/StockData/testing.csv"
df = pd.read_csv(tarCsv)
csv_parse = bt.feeds.GenericCSVData(dataname=tarCsv,
                        datatime=1,
                        open=2,
                        high=3,
                        low=4,
                        close=5,
                        volume=6,
                        openinterest=-1,
                        dtformat='%Y-%m-%d %H:%M:%S-05:00')
cerebro = bt.Cerebro()
cerebro.adddata(csv_parse)
cerebro.run()
cerebro.plot(iplot=False)

# tickerInfo, symbolList, symbolStr = fundamental()
# print(tickerInfo, symbolList, symbolStr)
# a = ABC(ib)

# for child in ib:
#     print(child)
# hisdata(symbolList)

# print(ib)

,Unnamed: 0,date,open,high,low,close,volume,average,barCount
0,0,2021-12-01 18:00:00-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
1,1,2021-12-01 18:00:05-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
2,2,2021-12-01 18:00:10-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
3,3,2021-12-01 18:00:15-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
4,4,2021-12-01 18:00:20-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
...,...,...,...,...,...,...,...,...,...
1435,1435,2021-12-01 19:59:35-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
1436,1436,2021-12-01 19:59:40-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
1437,1437,2021-12-01 19:59:45-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
1438,1438,2021-12-01 19:59:50-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0
1439,1439,2021-12-01 19:59:55-05:00,27.99,27.99,27.99,27.99,0.0,27.99,0

In [ ]:
import sys
sys.path.insert(1, './Fundamental/DilutionTracker')
from DtFilter import getDilutionData
import asyncio
 
await getDilutionData()

In [ ]:
import sys
sys.path.insert(1, "./HisData/DataDownload")
from HisData import hisData

hisData()